# Generated by Django 6.0.2 on 2026-02-24 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('regular', 'Regular Season'), ('r32', 'Round of 32'), ('r16', 'Round of 16'), ('qf', 'Quarterfinal'), ('sf', 'Semifinal'), ('f', 'Final')], default='regular', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('played_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('pending_confirmation', 'Pending Confirmation'), ('completed', 'Completed'), ('walkover', 'Walkover'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30)),
                ('walkover_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_confirmed', to=settings.AUTH_USER_MODEL)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_entered', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.season')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['scheduled_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('player1_games', models.IntegerField()),
                ('player2_games', models.IntegerField()),
                ('tiebreak_player1_points', models.IntegerField(blank=True, null=True)),
                ('tiebreak_player2_points', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='matches.match')),
            ],
            options={
                'ordering': ['set_number'],
                'unique_together': {('match', 'set_number')},
            },
        ),
    ]
