# Generated by Django 6.0.2 on 2026-02-24 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': [models.OrderBy(models.F('scheduled_date'), nulls_last=True), 'created_at'], 'verbose_name_plural': 'matches'},
        ),
        migrations.AlterField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='walkover_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='matchset',
            name='player1_games',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchset',
            name='player2_games',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchset',
            name='set_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchset',
            name='tiebreak_player1_points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchset',
            name='tiebreak_player2_points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
