# Generated by Django 6.0.2 on 2026-03-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_options_alter_match_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tier',
            field=models.IntegerField(blank=True, help_text="Tier this match belongs to; set from players' tier at match creation", null=True),
        ),
    ]
