# Generated by Django 6.0.2 on 2026-06-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0022_season_team_config_and_team_model'),
        ('matches', '0004_alter_match_player1_alter_match_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team1', to='leagues.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team2', to='leagues.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won_as_team', to='leagues.team'),
        ),
    ]
