# Generated by Django 6.0.2 on 2026-07-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_player1_alter_match_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending_confirmation', 'Pending Confirmation'), ('completed', 'Completed'), ('walkover', 'Walkover'), ('bye', 'Bye'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30),
        ),
    ]
