# Generated by Django 6.0.2 on 2026-07-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_backfill_bye_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_is_external',
            field=models.BooleanField(default=False, help_text='Set instead of player1 when this side is a player not registered in the system.'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_is_external',
            field=models.BooleanField(default=False, help_text='Set instead of player2 when this side is a player not registered in the system.'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_is_external',
            field=models.BooleanField(default=False, help_text='Set when the external player (rather than winner) won the match.'),
        ),
    ]
