# Generated by Django 6.0.2 on 2026-02-24 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayoffBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brackets_generated', to=settings.AUTH_USER_MODEL)),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playoff_bracket', to='leagues.season')),
            ],
        ),
        migrations.CreateModel(
            name='PlayoffSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_position', models.IntegerField(help_text='1-indexed position in the bracket')),
                ('round', models.CharField(choices=[('r32', 'Round of 32'), ('r16', 'Round of 16'), ('qf', 'Quarterfinal'), ('sf', 'Semifinal'), ('f', 'Final')], max_length=20)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='playoffs.playoffbracket')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playoff_slot', to='matches.match')),
                ('next_slot', models.ForeignKey(blank=True, help_text="Winner of this slot advances to next_slot's match", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_slots', to='playoffs.playoffslot')),
            ],
            options={
                'ordering': ['round', 'bracket_position'],
            },
        ),
    ]
