# Generated by Django 6.0.2 on 2026-02-24 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playoffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playoffslot',
            options={'ordering': ['bracket_position']},
        ),
    ]
