# Generated by Django 6.0.2 on 2026-03-01 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_season_num_tiers_seasonplayer_tier'),
        ('playoffs', '0002_alter_playoffslot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoffbracket',
            name='tier',
            field=models.IntegerField(default=1, help_text='Which tier this bracket is for (1-indexed)'),
        ),
        migrations.AlterField(
            model_name='playoffbracket',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playoff_brackets', to='leagues.season'),
        ),
        migrations.AlterUniqueTogether(
            name='playoffbracket',
            unique_together={('season', 'tier')},
        ),
    ]
