# Generated by Django 6.0.2 on 2026-02-24 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('sets_to_win', models.IntegerField(default=2, help_text='2 = best of 3, 3 = best of 5')),
                ('final_set_format', models.CharField(choices=[('full', 'Full Set'), ('tiebreak', 'Tiebreak'), ('super', 'Super Tiebreak')], default='full', max_length=20)),
                ('playoff_qualifiers_count', models.IntegerField(default=8)),
                ('walkover_rule', models.CharField(choices=[('winner', 'Winner gets all points'), ('split', 'Winner gets win points, loser gets walkover-loss points'), ('none', 'No points awarded')], default='winner', max_length=20)),
                ('postponement_deadline', models.IntegerField(default=14, help_text='Days allowed to reschedule')),
                ('points_for_win', models.IntegerField(default=3)),
                ('points_for_loss', models.IntegerField(default=0)),
                ('points_for_walkover_loss', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SeasonPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(blank=True, help_text='Initial seeding for playoffs', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_players', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_players', to='leagues.season')),
            ],
            options={
                'ordering': ['seed', 'player__last_name', 'player__first_name'],
                'unique_together': {('season', 'player')},
            },
        ),
    ]
