# Generated by Django 6.0.2 on 2026-02-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonplayer',
            options={'ordering': [models.OrderBy(models.F('seed'), nulls_last=True), 'player__last_name', 'player__first_name']},
        ),
    ]
