# Generated by Django 6.0.2 on 2026-03-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_alter_seasonplayer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='num_tiers',
            field=models.IntegerField(default=1, help_text='Number of competitive tiers in this season'),
        ),
        migrations.AddField(
            model_name='seasonplayer',
            name='tier',
            field=models.IntegerField(default=1, help_text='1-indexed tier number for this player in this season'),
        ),
    ]
