# Generated by Django 6.0.2 on 2026-03-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_season_num_tiers_seasonplayer_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='games_to_win_set',
            field=models.IntegerField(default=6, help_text='Games needed to win a set (typically 6, sometimes 8)'),
        ),
    ]
