# Generated by Django 6.0.2 on 2026-03-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_season_games_to_win_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='grace_period_days',
            field=models.IntegerField(default=7, help_text='Days after the scheduled date a match can be played without a formal postponement'),
        ),
    ]
