# Generated by Django 6.0.2 on 2026-03-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_add_grace_period_days_to_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='schedule_type',
            field=models.CharField(choices=[('single_day', 'Single day'), ('consecutive_days', 'Consecutive days'), ('weekly', 'Weekly')], default='weekly', max_length=20),
        ),
    ]
