# Generated by Django 6.0.2 on 2026-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_season_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='schedule_display_days',
            field=models.IntegerField(default=7, help_text='Days ahead to show when display mode is "Next X days"'),
        ),
        migrations.AddField(
            model_name='season',
            name='schedule_display_mode',
            field=models.CharField(choices=[('all', 'All upcoming matches'), ('current_week', 'Current week (+ overdue unplayed)'), ('next_x_days', 'Next X days (+ overdue unplayed)')], default='all', help_text='Which upcoming matches to show on the matchups page', max_length=20),
        ),
        migrations.AlterField(
            model_name='season',
            name='schedule_type',
            field=models.CharField(choices=[('single_day', 'Single day'), ('consecutive_days', 'Consecutive days'), ('weekly', 'Weekly')], default='weekly', help_text='How match days are spaced across the season', max_length=20),
        ),
    ]
