# Generated by Django 6.0.2 on 2026-03-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_add_schedule_display_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='schedule_display_mode',
            field=models.CharField(choices=[('all', 'All upcoming matches'), ('current_day', 'Current day (+ overdue unplayed)'), ('current_week', 'Current week (+ overdue unplayed)'), ('next_x_days', 'Next X days (+ overdue unplayed)')], default='all', help_text='Which upcoming matches to show on the matchups page', max_length=20),
        ),
    ]
