# Generated by Django 6.0.2 on 2026-03-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_add_current_day_display_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='display',
            field=models.BooleanField(default=True, help_text='Show this season in the dropdown for non-admin users who are not part of this season'),
        ),
    ]
