# Generated by Django 6.0.2 on 2026-04-12 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='1-indexed tier ordering')),
                ('name', models.CharField(help_text='Display name (e.g. Premier, Division 1)', max_length=50)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='leagues.season')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('season', 'number')},
            },
        ),
    ]
