# Generated by Django 6.0.2 on 2026-04-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_remove_season_num_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='playoffs_enabled',
            field=models.BooleanField(default=True, help_text='Show playoff bracket tab and admin playoff actions for this season'),
        ),
    ]
