# Generated by Django 6.0.2 on 2026-04-27 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_season_playoffs_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='preseason',
            field=models.ForeignKey(blank=True, help_text='Attach a previous season here to prevent rematches when generating the schedule — any matchup that already occurred in the attached season will be skipped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postseasons', to='leagues.season'),
        ),
    ]
