# Generated by Django 6.0.2 on 2026-04-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_season_playoffs_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='sponsor_logo',
            field=models.TextField(blank=True, help_text='Base64-encoded data URL of the sponsor logo (set via the admin upload field).'),
        ),
    ]
