# Generated by Django 6.0.2 on 2026-04-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_siteconfig_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='rules_content',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='show_rules',
        ),
        migrations.AddField(
            model_name='season',
            name='rules_content',
            field=models.TextField(blank=True, help_text='Rules text in Markdown format.'),
        ),
        migrations.AddField(
            model_name='season',
            name='show_rules',
            field=models.BooleanField(default=False, help_text='Show the Rules page in the navbar for this season.'),
        ),
    ]
