# Generated by Django 6.0.2 on 2026-04-27 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_add_preseason_to_season'),
        ('leagues', '0015_siteconfig_rules'),
    ]

    operations = [
    ]
