# Generated by Django 6.0.2 on 2026-05-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0018_season_win_by_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='enforce_scheduled_dates',
            field=models.BooleanField(default=True, help_text='Require matches past the grace period to be postponed before a result can be entered. When disabled, any match can be played regardless of its scheduled date.'),
        ),
    ]
