# Generated by Django 6.0.2 on 2026-06-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0019_season_enforce_scheduled_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='playoff_interval_days',
            field=models.IntegerField(default=7, help_text='Days between playoff rounds when scheduling with a start date'),
        ),
        migrations.AddField(
            model_name='season',
            name='playoffs_public',
            field=models.BooleanField(default=True, help_text='When enabled, all users can view playoff brackets. When disabled, only admins can see them.'),
        ),
        migrations.AddField(
            model_name='tier',
            name='playoff_qualifiers_count',
            field=models.IntegerField(blank=True, help_text="Qualifiers for this tier's bracket. Leave blank to use the season default.", null=True),
        ),
    ]
