# Generated by Django 6.0.2 on 2026-06-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0020_playoff_per_tier_and_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='is_playoffs',
            field=models.BooleanField(default=False, help_text='Tier is in playoff phase. Toggling on auto-generates the bracket; toggling off deletes it.'),
        ),
    ]
