# Generated by Django 6.0.2 on 2026-06-17 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0021_tier_is_playoffs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='players_per_team',
            field=models.IntegerField(default=1, help_text='1 = singles, 2 = doubles'),
        ),
        migrations.AddField(
            model_name='season',
            name='use_team_name',
            field=models.BooleanField(default=False, help_text='Display Team.name instead of concatenated member names (only relevant for doubles)'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='leagues.season')),
            ],
        ),
    ]
