# Generated by Django 6.0.2 on 2026-06-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0021_tier_is_playoffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='logo',
            field=models.TextField(blank=True, help_text='Overrides the global logo when this season is current (managed via admin upload). Leave blank to use the global setting.'),
        ),
        migrations.AddField(
            model_name='season',
            name='site_name',
            field=models.CharField(blank=True, help_text='Overrides the global site name when this season is current. Leave blank to use the global setting.', max_length=100),
        ),
    ]
