# Generated by Django 6.0.2 on 2026-06-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0022_season_branding_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='playoff_bracket_style',
            field=models.CharField(choices=[('traditional', 'Traditional (rounds left to right, final on the right)'), ('centered', 'Centered (draws converge from both sides, final in the centre)')], default='traditional', help_text='How the playoff bracket is laid out on the playoffs page.', max_length=20),
        ),
    ]
