# Generated by Django 6.0.2 on 2026-07-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0023_season_playoff_bracket_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='playoff_hide_scores',
            field=models.BooleanField(default=False, help_text='When enabled, playoff matches record only the winner — no set scores are captured or displayed.'),
        ),
    ]
