# Generated by Django 6.0.2 on 2026-07-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0024_season_playoff_hide_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='allow_external_players',
            field=models.BooleanField(default=False, help_text='Allow regular-season matches to be created against a player who is not in the system (name recorded only). External players appear in match results but never in standings.'),
        ),
    ]
